version: '3'
services:

  bee:
    image: iotaledger/bee:${BEE_VERSION:?BEE_VERSION is missing}
    container_name: iota-bee
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 16384
        hard: 16384
    stop_grace_period: 5m
    tty: true
    working_dir: /app
    ports:
      - "${BEE_GOSSIP_PORT:-15601}:${BEE_GOSSIP_PORT:-15601}/tcp"
      - "${BEE_AUTOPEERING_PORT:-14636}:${BEE_AUTOPEERING_PORT:-14636}/udp"
    labels:
      - "proxy.constraint=bee-${BEE_NETWORK:-mainnet}"
      - "traefik.enable=true"

      - "traefik.http.services.bee.loadbalancer.server.port=8081"
      - "traefik.http.services.bee.loadbalancer.healthCheck.path=/api/v1/info"
      - "traefik.http.services.bee.loadbalancer.healthCheck.interval=10s"
      - "traefik.http.services.bee.loadbalancer.healthCheck.timeout=3s"
      - "traefik.http.routers.bee.service=bee"
      - "traefik.http.routers.bee.rule=Host(`${BEE_HOST:?BEE_HOST is missing}`)"
      - "traefik.http.routers.bee.entrypoints=websecure"
      - "traefik.http.routers.bee.tls=true"
      - "traefik.http.routers.bee.tls.certresolver=myresolver"
      - "traefik.http.routers.bee.middlewares=redirect-dashboard"
      - "traefik.http.middlewares.redirect-dashboard.redirectregex.regex=^https:\\/\\/([^\\/]+)\\/?$$"
      - "traefik.http.middlewares.redirect-dashboard.redirectregex.replacement=https://$$1/dashboard/"
      - "traefik.http.middlewares.redirect-dashboard.redirectregex.permanent=true"
    cap_drop:
      - ALL
    command: [ "--config", "/app/config.json" ]
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${BEE_DATA_DIR:-./data}/storage:/app/storage"
      - "${BEE_DATA_DIR:-./data}/snapshots:/app/snapshots"
      - "${BEE_DATA_DIR:-./data}/config/config.chrysalis-${BEE_NETWORK:-mainnet}.json:/app/config.json:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "500m"

  ##################################################################
  #  Reverse Proxy and SSL                                         #
  ##################################################################

  traefik:
    image: traefik:v2.8.2
    container_name: iota-bee.traefik
    restart: unless-stopped
    command:
      - "--log.level=WARN"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.constraints=Label(`proxy.constraint`,`bee-${BEE_NETWORK:-mainnet}`)"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.transport.respondingTimeouts.readTimeout=10"
      - "--entrypoints.web.transport.respondingTimeouts.writeTimeout=10"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.transport.respondingTimeouts.readTimeout=10"
      - "--entrypoints.websecure.transport.respondingTimeouts.writeTimeout=10"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${ACME_EMAIL:-}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "${BEE_HTTP_PORT:-80}:80/tcp"
      - "${BEE_HTTPS_PORT:-443}:443/tcp"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "${BEE_DATA_DIR:-./data}/letsencrypt:/letsencrypt"
      - "./assets/traefik/${SSL_CONFIG:-letsencrypt}.yml:/etc/traefik/dynamic/config.yml:ro"
      - "${BEE_SSL_CERT:-./assets/traefik/certs/fake.cert}:/certs/domain.cert:ro"
      - "${BEE_SSL_KEY:-./assets/traefik/certs/fake.key}:/certs/domain.key:ro"
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
